### Site settings
title: Long-term stability of cerebrovascular reactivity varies across brain regions
author: Stefano Moia
email: smoia@bcbl.eu 
description: Long-term stability of cerebrovascular reactivity varies across brain regions # should be the same as "out_title"
baseurl: "/cvr-rel-var" # the subpath of your site: normally corresponds to the name of the repo
url: "https://smoia.github.io/cvr-rel-var" # the base hostname & protocol for your site: normally your github website

# Misc settings
featured-image-source:

# Build settings
markdown: kramdown
collections:
  - sections

### Social settings (Will appear in the footer)
500px_url:
facebook_url:
github_url: https://smoia.github.io
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/SteMoia

### Homepage tiles (The "In a nutshell" website part)
# This tells the website what data folder you're using. In this case, it's the folder "_sections"
tiles-source: sections # accepts "sections", "posts" or "pages"
tiles-count: 3

### Outreach Data
out_title: Long-term stability of cerebrovascular reactivity varies across brain regions # Real title
out_authors: Stefano Moia, Vicente Ferrer, Rachael C Stickland, Ross Markello, Eneko Uruñuela, Maite Termenon, César Caballero-Gaudes, Molly G. Bright # The authors
take_home: Long-term stability of CVR and its lag response presents patterns that are equally explained by vascular anatomy, neural activity, and anatomy.
# What follows is a list of downloadables that will appear after the take home message.
# The first one will also appear in the CTA (above the footer)
# They have to be in assets/downloadable
downloadable:
  - {name: Poster1, file: 3395_ISMRM_Moia.pdf, type: poster}
  - {name: Abstract, file: abstract.pdf, type: text}